services:
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379  
    env_file:
      - ./apps/backend/.env  

  redis:
   image: redis:7-alpine
   ports:
    - "6380:6379"    
  ai-service:
    build:
      context: ./apps/ai-service
    ports:
       - "8000:8000"  
    env_file:
      - ./apps/ai-service/llm/.env 

# http://llm:8000
