# golang:1.24-alpine
#         ↓
# copy go.mod/go.sum
#         ↓
# go mod download
#         ↓
# copy source code
#         ↓
# go build
#         ↓
# server binary
#         ↓
#         ↓
# alpine container
#         ↓
# copy ONLY server binary
#         ↓
# ./server

FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server .

# Runtime stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]

